-- Add soft delete column (deleted_at BIGINT DEFAULT 0) to regions, AI, and RAG schemas

-- Regions
ALTER TABLE IF EXISTS province ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS regency  ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS district ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS village  ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;

-- AI
ALTER TABLE IF EXISTS ai_config       ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS token_usage     ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS ai_request_logs ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;

-- RAG
ALTER TABLE IF EXISTS document_categories       ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS document_tags             ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS rag_configurations        ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS documents                 ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS document_chunks           ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS document_processing_jobs  ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS document_access_logs      ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS rag_query_history         ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS document_similarity_cache ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;